name: Waka Readme

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天午夜 (UTC) 自动运行

jobs:
  update-readme:
    name: Update Readme with Wakapi Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anmol098/waka-readme-stats@master # 或者使用 athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # --- Wakapi 服务器 ---
          API_BASE_URL: "https://wakapi.655353.xyz/api"
          
          # --- 其他可选配置 ---
          SHOW_TITLE: "true"
          TIME_RANGE: "last_7_days"
          SHOW_TIME: "true"
          SHOW_TOTAL: "true"
          SHOW_MASKED_TIME: "false"
          LANG_COUNT: "6" # 显示的语言数量
